---
title: "Monthly Numbers"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
---

```{r setup, echo = FALSE, warning=FALSE, message=FALSE}
source("monthlyreport_functions.R")
data <- read.csv('September2020trackingdata.csv')
tracking.data <-reformat_googlesheet(data)
tracking.data.month <- tracking.data[which(tracking.data$month=="September" & tracking.data$year=="2020"),]
```


### Hits by Program (Expanded View)
```{r, Hits by Type and Program, echo = FALSE, warning=FALSE, message=FALSE}
#expanded view
library("tidyr")
expanded.hits.draft <- hitsbyprogram(tracking.data.month)
expanded.hits <- expanded.hits.draft[,c("source", "Twitter", "fb", "other",
                                  "online.article", "radio", "tv")]
names(expanded.hits) <- c("Program", "Twitter", "Facebook", "Other ",
                          "Online Articles", "Radio", "TV")
#restrict data to CC, CM, CMN sources
expanded.hits.CMprograms <- subset(expanded.hits, Program=="CC"|Program=="CM"|Program=="CMN"|Program=="Total")
library("formattable")
expanded.hits.formatted <- formattable(expanded.hits.CMprograms,
                                       align=c("l", "c", "c", "c", "c", "c", "c"),
                                       list(''))
expanded.hits.formatted
```

### (Condensed View)
```{r, echo = FALSE, warning=FALSE, message=FALSE}
#condensed view
condensed.hits.draft <- expanded.hits.draft %>%
  as_tibble() %>%
  mutate(
    social=rt+tw+fb+other,
    stories=online.article+radio
  )
condensed.hits <- condensed.hits.draft[,c("source", "social", "stories", "tv")]
names(condensed.hits) <- c("Program", "Social Media", "Stories", "TV")

#restrict data to CC, CM, CMN sources
condensed.hits.CMprograms <- subset(condensed.hits, Program=="CC"|Program=="CM"|Program=="CMN"|Program=="Total")

#design into publishable table
library(formattable)
condensed.hits.formatted <- formattable(condensed.hits.CMprograms,align=c("l", "c", "c", "c"))

condensed.hits.formatted
```

### Hits by Region
```{r, echo = FALSE, warning=FALSE, message=FALSE}
#compute hits by regions
month.hitsbyregion <- hitsbyregion(tracking.data.month)

month.hitsbyregion
```

