---
title: "Content Use Highlights"
date: "Last updated: 8/17/2022"
output: 
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
---

```{css, echo=FALSE}
h1 {
  text-align: center;
}
```

# September 2022

**Erin Hassanzadeh** (WCCO in Minneapolis) dives into how Minneapolis is [climate-proofing its stormwater infrastructure](https://www.cbsnews.com/minnesota/news/minneapolis-stormwater-tunnel-overhaul/). 

**Steve MacLaughlin** (NBC6 in South Florida) uses the Climate Shift Index to explain how [climate change is impacting extreme heat](https://www.nbcmiami.com/weather/climate-shift-index-shows-impacts-of-climate-change-on-rising-temps-in-south-florida/2858220/) in Miami and around the country. 

**Mike Augustyniak** (WCCO in Minneapolis) attributes [warmer overnight fall lows](https://www.iqmediacorp.com/ClipPlayer/?ClipID=ed85f9cf-0658-4f35-9583-74f4cbb6de3b&ps=2) to climate change. 

**Eva Tesfaye** (WISC-TV in Madison) writes about how warming summer nights are hurting the [Midwest’s agriculture industry](https://www.channel3000.com/midwest-summer-nights-are-heating-up-and-thats-hurting-crops-and-livestock/).

**Steven Santana** (San Antonio Express-News) reflects on Texas’ [weather-vulnerable grid](https://www.mysanantonio.com/news/local/article/texas-power-outage-weather-17444071.php). 

**Miguel Almaguer** (NBC) connects worsening [wildfires to climate change-driven record heat](https://www.nbcnews.com/nightly-news/video/deadly-wildfire-historic-heat-blazing-through-the-west-147857477922?cid=sm_npd_nn_tw_nn) using Climate Central’s attribution research.

**Rachel Ramirez** (CNN) reviews how climate change may be causing a surge in [weather-related power outages](https://www.cnn.com/2022/09/14/us/power-outages-rising-extreme-weather-climate/index.html).

**Michael Behrens** (WZZM in Michigan) covers [fall warming trends](https://www.wzzm13.com/article/weather/despite-cool-start-fall-warming-trends-continue/69-667961f9-9de7-4918-88f8-f208886828e0) in Grand Rapids.



# August 2022

**Anthony Yanez** (KPRC in Houston) remembers Hurricane Harvey and breaks down [climate change attribution science](https://www.click2houston.com/weather/2022/08/26/5-years-later-how-harvey-became-a-monster-storm/). 

**Haley Bouley** (WFFF in Vermont) discusses the [dangers of rising humidity](https://www.iqmediacorp.com/ClipPlayer/?ClipID=7ea398f4-3166-4577-8390-8117955b8f41&ps=2). 

**Monique Robinson** (WFMY in Greensboro, NC) uses the [WeatherPower tool](https://www.iqmediacorp.com/ClipPlayer/?ClipID=6551b87c-f029-444a-b5cb-0abc6b5f3e5c&ps=2) to spotlight climate solutions.

**Tyler Sebree** (WSFA in Montgomery, AL) takes note of [stagnant air and air pollution in Alabama](https://www.wsfa.com/2022/08/10/number-annual-stagnant-days-are-increasing-alabama/).

**George Prentice** (Boise State Public Radio News) covers new research on [underestimated public climate concern](https://www.boisestatepublicradio.org/news/2022-08-23/idaho-global-warming-heat-boise-climate-change-boise) in Idaho and across the U.S.

**Brett Anthony** (CBS19 in Texas) forecasts [worsening algal blooms](https://www.cbs19.tv/article/sports/outdoors/texas-outdoors/hooked-on-east-texas/on-this-weeks-episode-of-hooked-on-east-texas-excessive-heat-toughens-the-battle-with-algae-blooms/501-312beff1-a4e0-4004-8278-23bf7237c8d8) in a warming world. 

**Matt Holiner** breaks down the nation’s [fastest-warming states](https://pantagraph.com/weather/watch-now-dry-weather-friday-across-illinois-but-rain-chances-coming-back-this-weekend/article_25221e32-0f24-11ed-ac66-038f3d95c5d7.html) for The Pantagraph in Illinois. 

**Brady Dennis** (The Washington Post) covers the [rise in rainfall extremes](https://www.washingtonpost.com/climate-environment/2022/08/06/many-places-are-seeing-more-intense-rainfall-thats-big-problem/) with rising temperatures.  

**Anne Thompson** (NBC News) covers the role of climate change in recent [heavy rainfall events](https://www.nbcnews.com/nightly-news/video/climate-change-devastating-many-areas-with-heavy-rainfall-flash-floods-145757253681). 

# July 2022

**Efren Afante** (WLTX in Columbia, SC) discusses how [warming and the urban heat island effect](https://www.iqmediacorp.com/ClipPlayer/?ClipID=4ff23fff-a83a-432d-99a0-94514143a203&ps=2) means more stagnant summer air.

**McCall Vrydaghs** (WHIO in Dayton, OH) connects climate change to more [pesky mosquitoes](https://www.iqmediacorp.com/ClipPlayer/?ClipID=d3613938-3c8e-4c7b-ba9f-ae06a74bbcca&ps=2).

**Matt Zaffino** (KGW in Portland, OR) breaks down Climate Central’s new [Climate Shift Index](https://drive.google.com/drive/folders/1UrShBxzrTsX9q6WRxLMjdGSo0CNj1GLQ). 

**Lauren Hope** (WBBH in Ft. Myers, FL) gives a tour of where [cities are headed by 2100](https://www.iqmediacorp.com/ClipPlayer/?ClipID=9f16e1c9-14fe-4221-8be1-d845ac62b4c8&ps=2)    due to climate change. 

**Skot Covert** (THV11 in Little Rock, Ark.) covers the recent rise in the number of days with [prime mosquito weather](https://www.thv11.com/article/sports/outdoors/mosquitos-showing-up-earlier-and-staying-longer-due-to-climate-change/91-0257e690-06e3-4d01-8a19-408cd5ff2806).

**Mary Landers** (Georgia Public Broadcasting), tries out our new [Climate Shift Index for coastal Georgia](https://www.gpb.org/news/2022/07/11/its-hot-normal-or-it-climate-change). 

**Catherine Marfin** (Dallas Morning News) discusses the relationship between [weather and climate change](https://www.dallasnews.com/news/weather/2022/07/18/how-does-this-years-heat-relate-to-climate-change-its-complicated-experts-say/). 

**Miles O'Brien** and **Will Toubman** (PBS News Hour)  cover how weather forecasters increasingly keep [audiences informed about climate change](https://www.pbs.org/newshour/show/weather-forecasters-increasingly-address-climate-change).

**Brendan Rivers** (WJCT in Jacksonville, Fla.) explains how climate change has contributed to the [rise in nighttime temperatures](https://news.wjct.org/first-coast/2022-07-05/nighttime-temperatures-are-on-the-rise-in-jacksonville-and-climate-change-is-to-blame) in Jacksonville.


# June 2022

**John Muyskens**, **Kasha Patel**, and **Naema Ahmed**, for The Washington Post, [highlight our new Climate Shift Index tool](https://www.washingtonpost.com/climate-environment/interactive/2022/maps-heat-wave-climate-change-us/) that can determine, in real time, the role climate change plays in making daily high temperatures more likely.

Meteorologist **Lauren Hope** is one of thousands to [show off](https://www.iqmediacorp.com/ClipPlayer/?ClipID=108999dc-9b5c-470e-b473-766a80fcf8dc&ps=2v) their climate stripes this #ShowYourStripes day.

**Cory Smith**, WLTX in South Carolina, [connects](https://www.wltx.com/article/weather/climate-change-adds-to-extreme-heat-in-the-south-climate-matters/101-c4af1c63-01f5-4396-a82f-d13cbc300143) climate change to extreme heat in the South. 

**Halle Parker** and **Priyanka Runwal**, reporting for WWNO in New Orleans, [cover](https://www.wwno.org/coastal-desk/2022-06-14/shrinking-wetlands-rising-seas-threaten-generations-of-tradition-for-louisiana-duck-hunters) the effects of rising seas and shrinking wetlands on duck hunting, a popular pastime in Louisiana.

**Robert A. Cronkleton**, for The Kansas City Star, explains why heavier rains and flooding are becoming more common in Kansas City. 
Meteorologist Rachel Duensing**, with WNCN in Raleigh, [warns](https://www.iqmediacorp.com/ClipPlayer/?ClipID=09eaf5c6-0d13-4ffe-a147-0c037ae3a50c&ps=2) of warming summers. 


# May 2022

**Sandy Hausman**, for WVTF National Public Radio, [discusses](https://www.wvtf.org/news/2022-04-28/study-shows-virginia-at-increased-risk-for-flash-floods-and-landslides) the increased risk for flash floods and landslides in Virginia.

Meteorologist **Haley Bouley** [explains](https://www.iqmediacorp.com/ClipPlayer/?ClipID=cd75d627-c93e-46ad-9242-b48bc04ead40&ps=2) how fire conditions are on the rise. 

**Maddie Burakoff**, from Spectrum News 1 in Milwaukee, [makes the climate connection](https://www.iqmediacorp.com/ClipPlayer/?ClipID=cd75d627-c93e-46ad-9242-b48bc04ead40&ps=2) between extreme rain, flood risks, and the need to build resilient infrastructure in Wisconsin.

**Skot Covert**, for THV11 in Little Rock, [explains](https://www.thv11.com/article/sports/outdoors/mosquitos-showing-up-earlier-and-staying-longer-due-to-climate-change/91-0257e690-06e3-4d01-8a19-408cd5ff2806) how warmer temperatures contribute to longer mosquito seasons.

**Susan Phillips**, for WHYY Philadelphia, [covers](https://whyy.org/articles/hotter-than-average-rainy-summer-noaa-prediction-philadelphia/) the summer heat forecasted for the Mid-Atlantic region and summer warming trends since 1970. 

Meteorologist **Erin Christiansen** at KMSB [tracks](https://www.iqmediacorp.com/ClipPlayer/?ClipID=4e3a1af5-90a8-4f2b-888c-a1e3dbf43e63&ps=2) groundwater conditions in Arizona.

# April 2022
Meteorologist **Iris Hermosillo**, with KNXV in Phoenix, [connects](https://www.iqmediacorp.com/ClipPlayer/?ClipID=36cd64fc-1b6c-4bfd-bcd0-4bbf37c18923&ps=20) melting winter snowpack to Arizona’s dismal water supply. 

CNN reporter **Rachel Ramirez** [covers](https://www.cnn.com/2022/03/29/weather/wildfires-texas-colorado-drought-climate/index.html) recent fires in Colorado and Texas and their links to ongoing drought. 

FOX32 meteorologist **Tim McGill** [explains](https://www.fox32chicago.com/weather/why-increasing-growing-degree-days-in-chicago-matters) why an increase in growing degree days in Chicago matters. 

**Evlondo Cooper** and **Ted MacDonald**, with Media Matters for America, [cover](https://www.mediamatters.org/broadcast-networks/2021-meteorologists-continued-play-key-role-national-and-local-broadcast-tv-news) the role of meteorologists in climate news coverage in 2021.

**Jim Dickey** [touts](https://www.iqmediacorp.com/ClipPlayer/?ClipID=ad36aab5-2615-48b2-a0ca-f8adc504514a&ps=2) the power of trees in reversing climate change for WZVN in Florida. 

# March 2022
AccuWeather senior meteorologist **Alan Reppert** [covers](https://climatecentral.cmail20.com/t/y-l-bthykz-irijurjjhj-jy/) how climate change affects the spring growing season and allergy forecast.

Chief meteorologist **Scott Dorval**, for Idaho News 6, [explains](https://climatecentral.cmail20.com/t/y-l-bthykz-irijurjjhj-jj/) which crops to plant in March given spring warming trends.

Meteorologist **Tyler Sebree** [visits](https://climatecentral.cmail19.com/t/y-l-btjkdky-irijurjjhj-yk/) the warming spring season for WSFA 12 News in Montgomery, Ala.

**Robert Cronkleton**, for The Kansas City Star, [covers](https://climatecentral.cmail19.com/t/y-l-btjkdky-irijurjjhj-yh/) recent record-high temperatures in Kansas City, part of long-term March warming trends in the city. 

**Josh Cingranelli** (WVIT - CT) [reports on](https://www.iqmediacorp.com/ClipPlayer/?ClipID=f0653c69-aa85-489e-b3cf-6837b6387e02&ps=2) how climate change can impact maple syrup production.

**Lauren Hope** (WBBH - FL) [uses](https://www.iqmediacorp.com/ClipPlayer/?ClipID=2ae1c77a-fa48-48e8-9aa1-22f7c934234f&ps=2) our Spring Package to discuss warmer spring temperatures in Fort Meyers, Fla.

# February 2022

CNN meteorologist **Tom Sater** [explains](https://climatecentral.cmail20.com/t/y-l-bjijjn-irijurjjhj-d/) the coastal impacts of rising sea levels by 2050.

**Heather Waldman**, for KCRA, [reports](https://climatecentral.cmail20.com/t/y-l-bjijjn-irijurjjhj-h/) on the impacts of climate change on the future of snow sports.

**Marc Tracy**, for the New York Times, [discusses](https://climatecentral.cmail19.com/t/y-l-byuikdy-irijurjjhj-b/) why the job of the TV weather person is getting more serious. 

**Dan Schwartz**, for the Atlantic, follows one of our fellow Climate Matters members, Meteorologist Shel Winkley (KBTX in Texas), in an [in-depth piece](https://climatecentral.cmail20.com/t/y-l-bjhhkky-irijurjjhj-jl/) about why “local meteorologists are better positioned than anyone else to talk their communities through the facts about climate change”.

**Glenn Schwartz** (WCAU - PA) [explains](https://www.iqmediacorp.com/ClipPlayer/?ClipID=e5fa2d85-9d93-4fe6-8659-242aad644c15&ps=2https://www.iqmediacorp.com/ClipPlayer/?ClipID=e5fa2d85-9d93-4fe6-8659-242aad644c15&ps=2) some of the signs of climate change and how we can curb emissions (WCAU - PA)  

**Ted Phaeton** (WJZY - NC)  [discusses](https://www.iqmediacorp.com/ClipPlayer/?ClipID=3fc44a17-2307-489c-ba71-b3990aabbc1b&ps=2) how climate change can affect the Winter Olympics

# January 2022

**John Deem**, for Greensboro News & Record, [explains](https://greensboro.com/news/local_news/winter-of-discontent-fooled-by-false-spring-triad-plants-are-blooming-too-early/article_1431776e-6cf7-11ec-b553-6f746e18ee1a.html) how some Triad plants were fooled by a “false spring”.

**Danielle Miller**, for WPMT, [interviews](https://www.fox43.com/article/weather/why-is-there-less-snow-in-pennsylvania-climate-change-warming-temperatures-snowfall-patterns/521-8cb50cea-4c33-4889-948b-cd0ea621eb9e) an expert on shifting snowfall patterns in Pennsylvania.

**Jeff Ranieri** (KNTV - CA) [informs](https://www.iqmediacorp.com/ClipPlayer/?ClipID=05b4070d-faab-4e26-abdb-603435f9a223&ps=2) his viewers on how to lower their carbon footprint in the home.

**Monica Woods** (KXTV - CA) [explains](https://www.iqmediacorp.com/ClipPlayer/?ClipID=7950b78f-a1d1-445a-9337-2d960e85ef70&ps=2) how climate change can cause record-setting snow and rain. 

**Blake Hansen** (WZZM - MI) [reports](https://www.iqmediacorp.com/ClipPlayer/?ClipID=05212207-162f-444b-a894-91322aa5ef8f&ps=2) the 2021 U.S. temperature rankings.


# December 2021

**Matt Pearl**, with WXIA in Atlanta, [discusses](https://www.wsfltv.com/news/national/two-americas/virtually-every-city-in-america-is-a-heat-island-heres-how-one-is-finding-its-voice) what the urban heat island effect means for residents of Mesa, Ariz. 

**Alix Martichoux**, for Nexstar in San Francisco, [reports](https://kfor.com/news/winter-feel-warmer-lately-in-these-places-it-really-is/) on warming winters across the country.

**Ayurella Horn-Muller**, **Brendan Rivers**, and **Danielle Uliano**, for ADAPT, [report](https://adaptflorida.org/rising-seas-swamp-black-spanish-and-indigenous-history-in-st-johns-county/) on sea level rise threats to historic landmarks that drive tourism in coastal Florida, using Climate Central analysis.

**Brian Kahn**, for Gizmodo, [writes](https://www.gizmodo.com.au/2021/11/the-gateway-to-rocky-mountain-national-park-is-on-fire-in-november/) about November wildfires in Colorado using Climate Central analysis of longer fire seasons.

**Scott Williams** (WTXF/FOX, PA) [explains](https://www.iqmediacorp.com/ClipPlayer/?ClipID=bafacb44-b831-4322-b267-248e4e633491&ps=2) how winters are working in Philadelphia.

**Greg Dee** (WFTS/ABC, FL) [discusses](https://www.iqmediacorp.com/ClipPlayer/?ClipID=15131ad8-8548-4ce4-8543-b4151596625e&ps=2) the connection between tornadoes and climate change.

**Haley Bouley** (WFFF/FOX, VT) [showcases](https://www.iqmediacorp.com/ClipPlayer/?ClipID=cfe86fb6-d305-43cc-93bf-85be33f67428&ps=2) how Christmas is warming over the year.


# November 2021

**Adriana Navarro**, for Accuweather, [discusses](https://www.accuweather.com/en/climate/wettest-days-on-record-getting-wetter-in-several-us-cities/1045692#:~:text=The%20intensity%20of%20extreme%20rainfall,higher%20risk%20of%20flood%20events.) how the wettest days on record are getting even wetter.

**Kaiti Blake**, for KSAT in San Antonio, [writes](https://www.ksat.com/weather/2021/10/25/bats-and-a-changing-climate-how-scientists-are-helping-an-endangered-species/) about how endangered bats are being affected by warmer temperatures. 

**Ayurella Horn-Muller** (Climate Central), **Brendan Rivers** (ADAPT) and **Danielle Uliano** (WJXT) [report](https://adaptflorida.org/fewer-fumes-what-the-switch-to-electric-vehicles-means-for-jacksonville/) on electric vehicles for Adapt Florida. 

**Maanvi Singh** and Climate Central’s **John Upton** and **Kaitlyn Weber** [report](https://www.theguardian.com/us-news/2021/nov/09/northern-california-wildfires-fire-weather-climate) on the rise in fire weather days in northern California for The Guardian.

**Charles Roop** (WCTV/CBS, FL) [explains](https://www.iqmediacorp.com/ClipPlayer/?ClipID=746ec9a5-1614-4eba-9942-28c4bf57fe48&ps=2) why we should care about COP26

**Samantha Jacques** (WZZM/ABC, MI) [uses](https://www.iqmediacorp.com/ClipPlayer/?ClipID=20c9a5ef-c15a-42b7-a728-696b1a20e3b4&ps=2) our Climate Change presentation to explain why climate change is simple, serious, and solvable. 

# October 2021

**Kerrin Jeromin**, for the Washington Post, [writes](https://www.washingtonpost.com/weather/2021/10/11/billion-dollar-disasters-2021-climate/) about the 18 billion-dollar weather disasters that have hit the U.S. this year.

What sea level rise will look like around the globe? **John Keefe and Rachel Ramirez**, for CNN, [answer that question](https://www.cnn.com/2021/10/12/world/3-degrees-sea-level-rise-climate-central/index.html) with Climate Central sea level rise tools and graphics.

In the wake of the Texas power concerns, **Frank Billingsley** [shows](https://www.click2houston.com/weather/2021/10/08/looking-for-power-look-up/) how renewables are scaling up and adding to the power mix in Houston and across Texas.

From Spectrum News in Columbus, Ohio, **Justin Gehrts** [highlights](https://spectrumlocalnews.com/me/maine/weather/2021/10/12/climate-central-climate-change-sea-level-rise-images) the risk from rising sea levels to iconic areas from Florida to New York.

**Grant Gilmore** (WTSP/CBS, FL) [showcases](https://www.iqmediacorp.com/ClipPlayer/?ClipID=98570a15-9916-4cb9-b02d-c21b2c15be8d&ps=2) future sea-level rise in the downtown Tampa.

**Katy Morgan** (WZTV/FOX, TN) [discusses](https://www.iqmediacorp.com/ClipPlayer/?ClipID=014c1610-2f82-46e8-a6e1-149e2844444e&ps=2) frequent billion-dollar disasters.

**Janice Huff** (WNBC/NBC, NY) [reports](https://www.iqmediacorp.com/ClipPlayer/?ClipID=709f022f-ff59-4b91-a9ef-ab776472bdce&ps=2) on Halloween extremes and October nights in New York City.

**Adam Epstein** (KTXL/FOX, CA) [interviews](https://www.iqmediacorp.com/ClipPlayer/?ClipID=36d82531-bfb7-4a8c-b0e7-e68fa34f2516&ps=2) our CEO **Dr. Benjamin Strauss** about future sea-level rise.

# Septmeber 2021

**Jordan Gass-Poore** produced CNN’s recent [“Chasing Life”](https://www.cnn.com/audio/podcasts/chasing-life?episodeguid=9ee6b0be-8213-46cb-96c2-ad9f01650108) podcast on how rising temperatures impact human health.

**Kate Williams** [reports](https://www.oregonlive.com/environment/2021/09/wildfire-smoke-latest-climate-crisis-to-hit-southern-oregon.html) on wildfire smoke and poor air quality for The Oregonian/Oregon Live. 

**Frank Kummer**, for the Philadelphia Inquirer, [explains](https://www.inquirer.com/science/climate/ida-climate-change-philadelphia-flooding-tornado-20210904.html) climate change helped “prime the pump” for a destructive Hurricane Ida.

**Mike Maze** (WRAL/NBC, NC) [discusses](https://www.iqmediacorp.com/ClipPlayer/?ClipID=7600688c-6f92-4925-9eb8-db9f27ffb243&ps=2) the impacts of drought and heatwaves on corn and soy crops.

**Miri Marshall** (WUSA/CBS, DC) [explains](https://www.iqmediacorp.com/ClipPlayer/?ClipID=9d86f6df-e16d-4a91-b288-763f5fa16ab8&ps=2) how heavy rainfall has been increasing over the years.

# August 2021

**Briana Zamora-Nipper**, for KPRC in Houston, [discusses](https://www.click2houston.com/news/local/2021/08/01/houston-ranked-among-the-top-5-hottest-metros-in-the-country/) the factors that make a city an urban heat island

**Maanvi Singh**, for The Guardian, [discusses](https://www.theguardian.com/us-news/2021/aug/25/wildfires-us-west-fire-weather-caldor) fire weather conditions and how they could have influenced the Caldor Fire.

**Beth Finello**, for WTTV in Indiana, [identifies](https://cbs4indy.com/weather/identifying-heat-related-illnesses-in-both-people-and-pets/) heat-related illnesses in both people and pets.

Another way to beat the summer heat in Boston — trees. Find out [how and why](https://www.boston25news.com/news/local-communities-planting-trees-offset-climate-change-consequences/YIX5XNUL5FAFDAHYBGQPRNFV3U/) from **Vicki Graf** and **Bob Dumas** at WFXT.

**Chester Lampkin** (WUSA/CBS, Washington, DC) [discusses](https://www.iqmediacorp.com/ClipPlayer/?ClipID=c3cf9f8e-93d8-491a-a4b8-e49454fd6d0a&ps=2) how carbon dioxide is warming our planet.

**Mike Nicco** (KGO/ABC, CA) [interviews](https://www.iqmediacorp.com/ClipPlayer/?ClipID=79658cc9-e3fa-4b96-8f23-7db27e9a0cdc&ps=2) our very own **Kaitlyn Weber** and **Andrew Perishing** about increasing fire weather days in the West.

**Alex Garcia** (KABB/FOX, TX) [calls on](https://www.iqmediacorp.com/ClipPlayer/?ClipID=2b89addb-b24d-4161-a10f-72de86c831e5&ps=2) climate scientist Dr. Kathryn Hayhoe to explain how climate change is affecting Texas.


# July 2021

**Rebecca Spiess**, for Denverite, [discusses](https://denverite.com/2021/07/13/denvers-heat-island-effect-boosts-city-temperatures-by-over-5-degrees/) the urban heat island effect in Denver, Colorado with input from Climate Central’s senior data analyst, **Jen Brady**. 

**Laura Klivans** [reported](https://www.kqed.org/science/1975879/more-heat-waves-coming-scientists-say-but-the-health-impacts-are-largely-preventable) on the increasing number of dangerous heat waves for KQED in the San Francisco Bay area.

**Efran Afante** (WLTX/FOX, SC) uses many of our graphics to help [explain](https://www.iqmediacorp.com/ClipPlayer/?ClipID=cf82ea40-69fb-4633-ba61-fde7787fd888&ps=2) how temperatures are rising in Columbia, South Carolina, and across the country.

**Andrea Michaels** (WPMT/FOX, PA) [makes the connection](https://www.iqmediacorp.com/ClipPlayer/?ClipID=750985b3-4866-4e04-84c1-479b53f26e5b&ps=2) between warmer summers and a longer mosquito and pollen season.

# June 2021

**Ashton Altieri**, for KCNC, 
[discusses](https://denver.cbslocal.com/2021/06/14/denver-seven-years-since-hot-temperatures-early/) the recent heatwave and record-breaking temperatures in Denver, Colorado. 

**Joe Martucci**, for The Press of Atlantic City, 
[reports](https://pressofatlanticcity.com/news/local/its-2021s-first-heat-wave-and-its-been-a-while-since-its-happened-this-early/article_050dbb00-c7a5-11eb-bdd1-ef708aca2f6f.html) on how heatwaves are becoming more common in Atlantic City, New Jersey.

**Jeff Beradelli**, for CBS News, 
[reports](https://www.cbsnews.com/news/mega-drought-california-extreme-fire-season/) on the “Mega-drought” in the West and how it can lead to a severe fire season this year.

**Brendan Rivers**, for WJCT, 
[uses](https://news.wjct.org/post/summer-heat-rise-jacksonville-due-climate-change) our Summer Package graphics to craft a well-rounded story on the warming summers in Jacksonville, Fla.

**Samantha Jacques** (WZZM/ABC, MI) 
[reports](https://www.iqmediacorp.com/ClipPlayer/?ClipID=c365aaef-8c13-4db8-afa1-63117f6335b3&ps=2) on the warming summer trend and the impacts of heat.

**Lena Dziechowski** (WSHM/CBS, MA) 
[shows](https://www.iqmediacorp.com/ClipPlayer/?ClipID=1164c751-c208-4f57-9ac7-f1a5ee1a01c2&ps=2) how the seasons are shifting due to climate change, making the summer season longer and hotter.

# May 2021

Meteorologists **Kyle Kiel**, **Brandon Libby**, and **Joie Bettenhausen**, for KWWL, [illustrate](https://climatecentral.createsend1.com/t/y-l-ojrttn-l-jd/) how new climate normals have changed in Iowa City. 

**Tom Davis**, for The Patch, [updates](https://climatecentral.createsend1.com/t/y-l-ojrttn-l-jh/) New Jerseyans on the Brood X cicadas, and how climate change can affect the timing of their emergence.
For the Cape May County Herald, **Shay Roddy** uses Climate Central’s Risk Finder tool to [illustrate](https://climatecentral.createsend1.com/t/y-l-ojtldtk-l-v/) how sea level rise is expected to impact Cape May’s coastal communities.

For Grist, **Shannon Osaka** [explains](https://climatecentral.createsend1.com/t/y-l-ojtldtk-l-e/) why warming temperatures due to climate change may be causing cicadas to emerge earlier.

**Bobby Deskins** (WTSP/CBS, FL) [shows](https://www.iqmediacorp.com/ClipPlayer/?ClipID=396d4cc4-340d-44ed-9997-dda9c021bb06&ps=2) how the new climate normals illustrate a warming trend across the country and in Tampa.

From the beach, **Elisa Raffa** [reports](https://www.iqmediacorp.com/ClipPlayer/?ClipID=a8f4a2ab-2c19-4390-b831-bff052d714e2&ps=2) on the impact of warming ocean temperatures.

# April 2021

**Zoe Nicholson**, for Greenville News, [reports](https://climatecentral.cmail19.com/t/y-l-oyucdl-tumitljkk-jj/) on the many climate change impacts that South Carolinians already face today.

In an ‘Impact Earth’ segment, **Amber Sullins** (KNXV/ABC, AZ) [explains](https://www.iqmediacorp.com/ClipPlayer/?ClipID=caa41d5e-298d-4a07-9b14-c69a83fff546&ps=2) how climate change is causing drought to last longer in the western United States.

**Justin Ballard**, for WREX in Illinois, [explains](https://climatecentral.cmail19.com/t/y-l-oyucdl-tumitljkk-jt/) how a warming climate can affect the emergence of cicadas.

**Janice Huff** [informs](https://www.iqmediacorp.com/ClipPlayer/?ClipID=b4e51cd1-78cd-439c-9130-783e3d3549eb&ps=2) her audience about the impending emergence of Brood X cicadas, and why warmer temperatures leads to earlier emergence.

For the Chesapeake Bay Magazine, **Emma Johnson** [reports](https://climatecentral.cmail19.com/t/y-l-oydhutd-tumitljkk-ji/) on earlier spring temperatures and the impact on the life cycle of the local Baltimore oriole species.

For Earth Day, **Matt Cavanaugh** [discusses](https://climatecentral.cmail19.com/t/y-l-oydhutd-tumitljkk-jd/) warming in Colorado Springs and how it exacerbates drought and wildfires in the area, for KRCC.


# March 2021

**Tracey Butler**, for WLS in Chicago, [explains](https://climatecentral.createsend1.com/t/y-l-oxihid-l-g/) how extreme heat is just as deadly and dangerous as the cold or storms with Climate Central’s Sean Sublette.

**Peta Sheerwood** (WRAL/NBC, NC) [explains](https://www.iqmediacorp.com/ClipPlayer/?ClipID=d2f36f12-9910-4977-9e99-9bdb8ce2326c&ps=2) how climate change is making for more days of above-average spring temperatures in Raleigh.

**Deitra Tate**, for Spectrum News 1, [gives examples](https://climatecentral.createsend1.com/t/y-l-oxihid-l-w/) of how a warming climate can disrupt phenology, or the timing of natural events, across the U.S.

**Weather.com** [highlights](https://climatecentral.createsend1.com/t/y-l-oxjhtk-l-yh/) that summers are trending hotter along with their 2021 summer temperature outlook.

**Chris Easlick** (WNEM/CBS, MI), for WNEM in Michigan, [investigates](https://www.iqmediacorp.com/ClipPlayer/?ClipID=11d98e76-0e90-4da7-9b6d-fbb22cf4a3fe&ps=2) the declining ice coverage of the Great Lakes by interviewing fishing locals and academic experts

# February 2021

**Sammy Roth**, for the Los Angeles Times, [discusses](https://climatecentral.createsend1.com/t/y-l-obyhx-l-jh/) how Texas’ power grid, in light of the recent winter storm, isn’t prepared for climate change. 

**Megan Salois** (WHO/NBC, IA) [answers](https://www.iqmediacorp.com/ClipPlayer/?ClipID=90eff97f-609b-4b49-8966-e383ab204985&ps=2) a viewer’s question about climate change, using our graphic to explain how cold spells still happen in a warming climate.

**Bob Henson** [explains](https://climatecentral.createsend1.com/t/y-l-obyhx-l-jk/) how the U.S electric grid is uniquely susceptible to power outages — a problem that is expected to worsen with climate change, for Yale Climate Connections.

**Mike Estime** (WJBK/FOX, MI) [discusses](https://www.iqmediacorp.com/ClipPlayer/?ClipID=3fc2f36d-5427-4223-912b-2d87897db60b&ps=2) ice coverage on the Great Lakes, and how popular pastimes like ice fishing and ice hockey may be under threat.

# January 2021

**Kevin Janison** (KSNV/NBC, NV) [covers](https://www.iqmediacorp.com/ClipPlayer/?ClipID=51cb7742-20fb-46ff-b00c-c95d3e2301b7&ps=2) 2020 heat records in Nevada and globally.

**Dawn Stover** [covered](https://thebulletin.org/2021/01/broken-record-the-planet-is-getting-hotter-and-hotter-and-hotter/) the release of 2020 global temperatures and tied in a Climate Central release on warming winters to explain the pervasive impacts of climate change, in The Bulletin.

**Raphael Miranda** (WNBC/NBC, NY) [explains](https://www.iqmediacorp.com/ClipPlayer/?ClipID=21c35067-7ac3-488b-894d-b7e1eb4217cd&ps=2) the trend of fewer colder nights in the city, as a result of climate change.

For The Press of Atlantic City, **Buzz Keough** [highlights](https://climatecentral.createsend1.com/t/y-l-oldhjil-l-yk/) our sea-level rise and affordable housing study in regard to the challenges that Atlantic City and Ocean City, NJ will face.

**Rebecca Thiele** [reports](https://climatecentral.cmail19.com/t/y-l-olhklyk-tumitljkk-yk/) for WFYI on how global climate change is having local impacts in Indiana, such as heavier rain events. 

# December 2020

**James Bruggers** [outlines](https://insideclimatenews.org/news/09122020/georgia-senate-ossoff-perdue-warnock-loeffler-climate-hurricane-drought-sea-level-rise/) how climate change is on the ballot in Georgia, and features an interview with Climate Central's Sean Sublette, for InsideClimate News.

For The Guardian, **Oliver Milman** [discusses](https://www.theguardian.com/environment/2020/dec/01/climate-crisis-triple-flooding-threat-low-income-us-homes-by-2050) Climate Central’s recent affordable housing and sea level rise paper and its implications across the different coastal states. 

**Kristen Kirchhaine** for WTMJ, [interviews](https://www.tmj4.com/news/local-news/warming-winters-how-climate-change-is-affecting-southeast-wisconsin) one of our recommended experts Dr. Michael Notaro to explain how climate change is impacting winter in Southeast Wisconsin.

**Allen Best** [investigates](https://mountaintownnews.net/2020/12/10/colorado-icebox-notably-warmer/) why average winter temperatures over the decades in Denver are not as pronounced as the state of Colorado, for Mountain Town News. 

**Adam Epstein** (KTXL/FOX, CA) [explains](https://www.iqmediacorp.com/ClipPlayer/?ClipID=8305f00a-5cc1-4111-ba61-c8616bcfe290&ps=2) the concept of “getting to Net Zero” and how we might go about lowering our carbon emissions.

**Al Roker** (WNBC/NBC, National) [covers](https://www.iqmediacorp.com/ClipPlayer/?ClipID=5829b5ef-5dfe-4837-af8f-f0b904e684c2&ps=2) western wildfires, a “rare December threat”, explaining how climate change is leading to drier conditions and extending the fire season.

**Carl Parker** (The Weather Channel, National) [discusses](https://www.iqmediacorp.com/ClipPlayer/?ClipID=ede23fd2-4e9f-42db-a0a9-fcdf050927e9&ps=2) billion-dollar disasters, and how these extreme weather events are taking a severe toll on American farmers.

**Kenton Gewecke** (KOMU/NBC) [continues](https://www.komu.com/weather/showmeclimate/warm-december-days-are-becoming-more-common/article_706dd2b2-3b47-11eb-b1c9-b39366de3047.html?fbclid=IwAR302CeW9-YzL107D2wf7C7wa8hepg8dtqtzLhhfdRehqNWnVQm6EC9QVwE) his ‘Show me Climate’ segment by using an RtC graphic he received in order to discuss how climate change is making warm December days more common.

***

# November 2020

**Amelia Draper** (WRC, DC) is a Climate Matters superstar! In November she produced 14 on-air climate change segments, 9 of which used our content. One [example](https://www.iqmediacorp.com/ClipPlayer/?ClipID=34225850-e5f2-4ef8-845f-21f32467fd22&ps=2) is her piece on shorter winter cold snaps. You can find more examples on the NBC ‘Changing Climate’ [site](https://www.nbcwashington.com/news/local/changing-climate/).

**Ryan Hanrahan** (WVIT, CT) [explains](https://www.iqmediacorp.com/ClipPlayer/?ClipID=894fb4b5-248d-4074-827c-be8916cc42d3&ps=2) how Hartford, CT, has warmed since the 1970s, using a graphic he received the previous day in an RtC alert.

For The Guardian, **Nina Lakhani** [reports](https://www.theguardian.com/environment/2020/nov/12/scorching-tucson-bucks-us-trend-to-put-climate-justice-at-centre-of-plans) on the mounting efforts to introduce renewables to Tucson, Ariz. and fight climate change.

For WRGB/CBS, **Steve LaPointe** [details](https://cbs6albany.com/weather/weather-extra/winters-are-warming-and-climate-change-is-the-driver) how climate change is a main driver of the warming winters in New York and New England. 

For the Arizonia Republic, **Emily Wilder** [connects](https://www.azcentral.com/story/news/local/phoenix-weather/2020/11/17/phoenix-again-breaks-record-latest-90-plus-degree-heat-year/6327151002/) the record heat in Phoenix to climate change and the urban heat island effect.

**David Dickson** (WCBD, SC) uses a range of Climate Matters resources in his news segment, ‘A Moment of Science’, to [explain](https://www.iqmediacorp.com/ClipPlayer/?ClipID=e4af31c8-87aa-489a-8643-ca0e3394d413&ps=2) the science of climate change and its impacts.

***

# October 2020

**Mike Favetta** (Spectrum News NY 1, NY) [discusses](https://www.ny1.com/nyc/all-boroughs/weather-news/2020/10/06/energy-disruptions-are-more-frequent-due-to-extreme-weather) how climate change and extreme weather increases the risk of energy disruptions. 

**Maria Esquinca** (Remezcla) provides a [detailed analysis](https://remezcla.com/features/culture/climate-change-texas/) of how climate change is disproportionately affecting black and brown communities in Texas.

**Sammy Roth** (LA Times, CA) of the [reports](https://docs.google.com/document/d/195vBP04UlkBK7jf5zxS2Q5E6G35I1P339bvyuAsNTBs/edit#) how climate change is a threat to the California power grids.

Covering the election, **Joe St. George** interviewed voters about their views on climate change and [cites](https://www.iqmediacorp.com/ClipPlayer/?ClipID=b59ba82c-8aea-4048-9fca-9acc50c12b03&ps=2) Climate Central sea level rise statistics (which aired across many NBC and ABC stations).

**Cecy del Carmen** (WBTS, MA) [explains](https://www.iqmediacorp.com/ClipPlayer/?ClipID=6eec9bb3-97a8-4c62-b8ce-f65767633338&ps=2) how climate change is giving rise to more frequent power outages -- particularly in the Northeast.

**Darren Peck** (KPIX, CA) [breaks down](https://www.iqmediacorp.com/ClipPlayer/?ClipID=70401b37-93d4-4db8-87ea-7cded8a33d34&ps=2) the role of climate change in this year’s catastrophic wildfires in California, explaining how a warmer atmosphere leads to a drier landscape.


***

# September 2020  

As part of the annual September Climate Week, **Janice Huff** (WNBC, NY) “[schools us](https://www.iqmediacorp.com/ClipPlayer/?ClipID=33030365-9313-4456-bffb-fadd4521c7f0&ps=2)” on how our changing climate is making for stronger Atlantic storms.

**John Morales** (WTVJ, FL) [reports](https://www.iqmediacorp.com/ClipPlayer/?ClipID=8db22313-42ec-4018-ba5b-a84b7c91a985&ps=2) on how extreme heat due to climate change is disproportionately impacting low-income communities in Miami.

**Jeff Berardelli** (WCBS, NY) [explains](https://www.cbsnews.com/news/wildfire-climate-change-extreme-weather/) the link between worsening wildfires and climate change (which happened to be briefly featured on 'Late Night with Seth Meyers').

**Ariana Brocious** (Arizona Public Media, AZ) [discusses](https://news.azpm.org/p/news-topical-nature/2020/9/4/179760-the-risks-of-severe-heat/) the health risks of severe heat in Tucson, which are particularly threatening to the city's low-income residents.

**Jeff Ranieri** (KNTV/NBC, CA) “puts some numbers” on the story of climate change, [using our graphic](https://www.iqmediacorp.com/ClipPlayer/?ClipID=e5ddbbea-c9a9-4cee-b3a8-69dae0f616fa&ps=2) to explain how increasing average temperatures are making for larger wildfires.

**Haddie McLean** (WISC/CBS, WI) [explains](https://www.iqmediacorp.com/ClipPlayer/?ClipID=f75a1d04-4087-4a7d-89e8-7d310229b3cb&ps=2) how record high temperatures have been outpacing record lows in Madison, due to our warming climate.

***

# August 2020  

**Debra Utacia Krol** (Arizona Republic) [used](https://www.azcentral.com/in-depth/news/2020/08/26/heat-killing-more-people-cities-sizzle-hotter-temperatures/4553439002/) data from our [extreme heat analysis](https://medialibrary.climatecentral.org/resources/2020-days-above-thresholds) last month for their own interactive map, to help illustrate the worsening extreme heat in Phoenix, Arizona.

**Ian James** (Arizona Republic) [explained](https://www.azcentral.com/story/news/local/arizona-environment/2020/08/28/how-climate-change-making-wildfires-worse-across-west/5643391002/) the linkage between the ongoing western wildfires and climate change.

**Jorges Torres** (KNXV/ABC) made use of his RtC email to [highlight](https://www.iqmediacorp.com/ClipPlayer/?ClipID=e03f22ca-9fe4-4eb3-8e54-b2b3e844454a&ps=2) how the extreme heat in Phoenix is part of a trend, due to our warming climate.

**Joe Martucci** (Press of Atlantic City) enlisted Sean's help to [report](https://pressofatlanticcity.com/weather/climate-change-links-stronger-storms-to-jersey-shore-but-not-more/article_b305f9dd-e2dc-5677-9fb4-2ab9128ac4f1.html) on how warmer oceans make for stronger storms in New Jersey.

**Ben Cathey** (WVLT/CBS) [interviewed](https://www.iqmediacorp.com/ClipPlayer/?ClipID=4fdcae6d-5461-41e2-b023-c14e448fd84f&ps=2) our national expert on Poison Ivy, Dr Jacqueline Mohan, for his on-air story on worsening poison ivy due to elevated CO2 levels.

**Miri Marshall** (WUSA/CBS) [outlined](https://www.iqmediacorp.com/ClipPlayer/?ClipID=59be4a13-d8c4-4130-bcf9-ce744aa4fe75&ps=2) how poison ivy is becoming more toxic due to elevated atmospheric CO2 levels. Ben Cathey (WVLT/CBS) also covered the story on air, and [interviewed](https://www.iqmediacorp.com/ClipPlayer/?ClipID=4fdcae6d-5461-41e2-b023-c14e448fd84f&ps=2) our national expert on Poison Ivy, Dr Jacqueline Mohan.

**Eric Sorensen** (WQAD/ABC) [warned](https://www.iqmediacorp.com/ClipPlayer/?ClipID=674db910-76f9-4abb-8cd5-2762f7fbf2d8&ps=2) his viewers that, if they were going hiking, our warming climate is making for an ever-increasing risk of developing Lyme Disease.


***
