---
title: "Monthly Numbers"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
---

<style type="text/css">
.title {
  display: none;
}

</style>

<div class="row" style="padding-top: 30px;">
<div class="col-sm-14">

```{css, echo=FALSE}
h1 {
  text-align: center;
}
```

```{r setup, echo = FALSE, warning=FALSE, message=FALSE}
source("monthlyreport_functions.R")
data <- read.csv('Sept2020TrackingData.csv')
tracking.data <-reformat_googlesheet(data)
tracking.data.September2020 <- tracking.data[which(tracking.data$month=="September" & tracking.data$year=="2020"),]
```

***

# **September 2020**

Repository for CM/N Programs Monthly Tracking report.

### Hits by Program
```{r, Hits by Type and Program, echo = FALSE, warning=FALSE, message=FALSE}
#expanded view
library("tidyr")
expanded.hits.draft <- hitsbyprogram(tracking.data.September2020)
expanded.hits <- expanded.hits.draft[,c("source", "Twitter", "fb", "other",
                                  "online.article", "radio", "tv")]
names(expanded.hits) <- c("Program", "Twitter", "Facebook", "Other ",
                          "Online Articles", "Radio", "TV")
#restrict data to CC, CM, CMN sources
expanded.hits.CMprograms <- subset(expanded.hits, Program=="CC"|Program=="CM"|Program=="CMN"|Program=="Total")
library("formattable")
expanded.hits.formatted <- formattable(expanded.hits.CMprograms,
                                       align=c("l", "c", "c", "c", "c", "c", "c"),
                                       list(''))
expanded.hits.formatted
```

### Top 10 Releases
```{r, Sept 2020 Top 10 Releases, echo = FALSE, warning=FALSE, message=FALSE}
rankedreleases.September2020 <- rankReleases(tracking.data.September2020)
top10releases.September2020 <-rankedreleases.September2020[c(1:10),]
library("formattable")
names(top10releases.September2020) <- c("Release", "Social", "Stories", "TV", "Total")
formattable(top10releases.September2020)
```


### Hits by Region
```{r, echo = FALSE, warning=FALSE, message=FALSE}
#compute hits by regions
month.hitsbyregion <- hitsbyregion(tracking.data.September2020)

month.hitsbyregion
```

***

# **August 2020**

```{r, echo = FALSE, warning=FALSE, message=FALSE}
tracking.data.August2020 <- tracking.data[which(tracking.data$month=="August" & tracking.data$year=="2020"),]
```

### Hits by Program
```{r, August 2020 Hits by Program, echo = FALSE, warning=FALSE, message=FALSE}
#expanded view
library("tidyr")
expanded.hits.draft.August2020 <- hitsbyprogram(tracking.data.August2020)
expanded.hits.August2020 <- expanded.hits.draft.August2020[,c("source", "Twitter", "fb", "other",
                                  "online.article", "radio", "tv")]
names(expanded.hits.August2020) <- c("Program", "Twitter", "Facebook", "Other ",
                          "Online Articles", "Radio", "TV")
#restrict data to CC, CM, CMN sources
expanded.hits.CMprograms.August2020 <- subset(expanded.hits.August2020, Program=="CC"|Program=="CM"|Program=="CMN"|Program=="Total")
library("formattable")
expanded.hits.formatted.August2020 <- formattable(expanded.hits.CMprograms.August2020,
                                       align=c("l", "c", "c", "c", "c", "c", "c"),
                                       list(''))
expanded.hits.formatted.August2020
```

### Top 10 Releases
```{r, echo = FALSE, warning=FALSE, message=FALSE}
rankedreleases.August2020 <- rankReleases(tracking.data.August2020)
top10releases.August2020 <-rankedreleases.August2020[c(1:10),]
library("formattable")
names(top10releases.August2020) <- c("Release", "Social", "Stories", "TV", "Total")
formattable(top10releases.August2020)
```

### Hits by Region
```{r, August 2020 Hits By Region, echo = FALSE, warning=FALSE, message=FALSE}
#compute hits by regions
month.hitsbyregion.August2020 <- hitsbyregion(tracking.data.August2020)
month.hitsbyregion.August2020
```

***

```{r, TV Goals, echo = FALSE, warning=FALSE, message=FALSE}
#subset 2020 data
  data2020 <-tracking.data[which(tracking.data$year=="2020"),]
  #replace NAs in tv column with 0s
  data2020$tv[is.na(data2020$tv)] <- 0
  #summarize tv by month
  library("dplyr")
  tvbymonth <- data2020 %>%
    group_by(month) %>%
    summarise(tv=sum(tv))
  #add 20% to tv
  tvbymonth$tv <- tvbymonth$tv*1.2
  #order data by month
  library("dplyr")
  tvbymonth$month <- factor(tvbymonth$month, levels=month.name)
  #c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
  library("tidyverse")
  tvbymonth$month <- sort(tvbymonth$month)
  #add column for cumulative sum of tv airings
  tvbymonth$cumulative.tv <- cumsum(tvbymonth$tv)
  tvbymonth <- as.data.frame(tvbymonth)
  #tv goals
  tv.goals <- c(500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000, 5500, 6000)
  month <- month.name
  tvgoals.bymonth <- data.frame(month, tv.goals)
  #merge hits and goals
  tvgoalsandhits <- merge(tvbymonth, tvgoals.bymonth, by="month", all.y = TRUE)
  #remove tv column
  tvgoalsandhits <- subset(tvgoalsandhits, select=-tv)
  #reorder columns
  tvgoalsandhits <- tvgoalsandhits[,c(1,3,2)]
  #melt dataframe
  library("reshape2")
  melted.tvgoalsandhits <- melt(tvgoalsandhits)
  #make variable a factor
  melted.tvgoalsandhits$variable <- factor(melted.tvgoalsandhits$variable, levels = c("tv.goals", "cumulative.tv"))
  melted.tvgoalsandhits$variable <- sort(melted.tvgoalsandhits$variable)
  #plot chart
  library("ggplot2")
  tvgoalschart <- ggplot(melted.tvgoalsandhits, aes(month, value, group=variable)) + 
    theme(axis.text.x = element_text(angle=45, vjust=0.7)) +
    geom_line(aes(color=variable)) +
    labs(y="TV Airings", x="") +
    scale_fill_discrete(name="", labels=c("Goals", "Cumulative Airings"))
  
  tvgoalschart
```


